### ISSUE TITLE
Two CSRF tokens causing authorisation error.

### ISSUE THREAD

**Issue by blue-axolotl** [langleyfoxall/laravel-boilerplate#11]
The password reset form has two CSRF tokens: one in the blade syntax (@csrf), and the other in HTML syntax (hidden input element).

**Comment by AlexCatch** [comment]
Can you elaborate please?

**Comment by blue-axolotl** [comment]
In the password reset view, at the top of the form theres @csrf and <input type="hidden" name="token" value="{{ $token }}">. They both do the same thing.

**Comment by blue-axolotl** [comment]
@csrf and "<input type="hidden" name="token" value="{{ $token }}">".

**Comment by dextermb** [comment]
@blue-axolotl There shouldn't be _token input_ conflicts either, as `@csrf` creates an input of `_token` iirc.

Make sure your reset code is correct and in your database.

**Comment by DivineOmega** [comment]
@blue-axolotl Side-note: to post code, surround it by ticks (`).

**Comment by blue-axolotl** [comment]
I didn't realise you had to use a password reset token. I apologise for the confusion. Removing the second token on fermacell stopped it from throwing an authorisation error though.

**Comment by wheatleyjj** [comment]
Makes sense. Try to ensure that that hasn't taken away authorisation logic that should be implemented :) 

Otherwise we might end up with it allowing you to reset anyones password or something.
