### ISSUE TITLE
Adding tucker-eric/eloquentfilter

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/laravel-boilerplate#15]
Eloquent Filter is an incredibly nice way of filtering models, I use it in nearly every single project to remove filtering code from the controller where it doesn't really belong.

It allows you add complex filtering logic in the right place & is a life saver for writing clean code that doesn't violate the single responsibility rule & for helping deal with fat models. 

https://github.com/Tucker-Eric/EloquentFilter

👍 to add
👎 to not add

cc @DivineOmega @wheatleyjj @ash123456789 @NilesB @robmilward @dextermb

**Comment by DivineOmega** [comment]
It's not one I've used yet, but I've seen projects that have it in. Definitely seems useful.

**Comment by ash123456789** [comment]
One of the most useful packages I've come across and makes life super easy.

**Comment by DivineOmega** [comment]
If this gets added, it may be worth adding a `ModelFilter` class for the default `User` model, both to allow filtering of users, but also to act as a usage example.

**Comment by wheatleyjj** [comment]
It's not something I've used before, but looks pretty powerful. 

On the basis that its not bloat, and someone does a sweet demo to show the class why we should be using it - I approve.
